version: '3'

services:
  client:
    build:
      context: ./client
    # image: client8200
    # volumes:
    #   - ./client/dist:/dist
    ports:
      - 3000:80

  server:
    # build:
    #   context: ./server
    image: server8200
    volumes:  
      - ./server/dist:/app/dist
    ports:
      - "3001:4000"  

  db-postgres:
    image: db-postgres8200
    ports:
      - "27017:27017"
